[package]
name = "tobari-shell"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "tobari"
path = "src/main.rs"

[dependencies]
tobari-ipc = { path = "../core/crates/tobari-ipc" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
cef = { version = "0.1", optional = true }
cef-dll-sys = { version = "0.1", optional = true }

[features]
default = []
cef-ui = ["dep:cef", "dep:cef-dll-sys"]

[profile.release]
lto = true
codegen-units = 1
strip = true
